"""Weeks 14-15: build the final report and the presentation pack.

Everything here reads artifacts that earlier weeks wrote to ``reports/``.
No number is typed in by hand, so the report cannot drift away from the
model that was actually trained.
"""

from pathlib import Path

import pandas as pd

from .config import TARGET_R2


def rupees(value):
    """Format a rupee amount with Indian-style grouping."""
    try:
        value = float(value)
    except (TypeError, ValueError):
        return str(value)

    negative = value < 0
    digits = "{0:.0f}".format(abs(value))
    if len(digits) > 3:
        head, tail = digits[:-3], digits[-3:]
        groups = []
        while len(head) > 2:
            groups.insert(0, head[-2:])
            head = head[:-2]
        if head:
            groups.insert(0, head)
        digits = ",".join(groups + [tail])
    return "Rs {0}{1}".format("-" if negative else "", digits)


def markdown_table(frame, float_format="{0:.4f}"):
    """Render a DataFrame as a GitHub-flavoured Markdown table."""
    frame = frame.copy()
    for column in frame.columns:
        if pd.api.types.is_float_dtype(frame[column]):
            frame[column] = frame[column].map(
                lambda v: "" if pd.isna(v) else float_format.format(v)
            )
        else:
            frame[column] = frame[column].astype(str)

    header = "| " + " | ".join(frame.columns) + " |"
    divider = "| " + " | ".join(["---"] * len(frame.columns)) + " |"
    rows = ["| " + " | ".join(row) + " |" for row in frame.astype(str).values]
    return "\n".join([header, divider] + rows)


def read_csv(path, **kwargs):
    path = Path(path)
    return pd.read_csv(path, **kwargs) if path.exists() else None


def objective_verdict(measured_r2, target=TARGET_R2):
    """State plainly whether the documented R2 objective was met."""
    if measured_r2 >= target:
        return "MET", (
            "The measured test R2 of {0:.4f} meets the documented objective "
            "of {1:.2f}.".format(measured_r2, target)
        )
    return "NOT MET", (
        "The measured test R2 of {0:.4f} is below the documented objective of "
        "{1:.2f}. The paragraphs below explain why the objective is not "
        "reachable on the eight-column schema and what would be required to "
        "reach it.".format(measured_r2, target)
    )


def build_final_report(context):
    """Assemble the Week 14 report from the artifacts of Weeks 5-13."""
    lines = []
    add = lines.append

    add("# Used Car Price Prediction - Final Project Report")
    add("")
    add("Foundation of Machine Learning (SEML3211)")
    add("")
    add("Generated by `scripts/week14_final_report.py`. Every figure below is")
    add("read from the artifacts produced by the pipeline run recorded at")
    add("`{0}`.".format(context.get("created_at", "unknown")))
    add("")

    add("## 14.1 Dataset")
    add("")
    add(markdown_table(context["cleaning_summary"], "{0:.0f}"))
    add("")
    add(
        "The cleaned dataset contains {0:,} unique vehicle records across {1} "
        "original attributes, with {2} missing values.".format(
            context["clean_records"],
            len(context["base_columns"]),
            context["missing_values"],
        )
    )
    add("")

    add("## 14.2 Features")
    add("")
    add(markdown_table(context["feature_catalogue"]))
    add("")
    add(
        "`car_age` is measured against a reference year of {0}, which is the "
        "latest manufacturing year present in the training split. That value "
        "and the training-set name frequencies are stored inside the model "
        "bundle so predictions use the same numbers the model was fitted on."
        .format(context["reference_year"])
    )
    add("")

    add("## 14.3 Baseline models (Weeks 9-10)")
    add("")
    add(markdown_table(context["baseline_results"]))
    add("")
    add(
        "Models are ranked by `CV_R2_mean`, the mean R2 across {0}-fold "
        "cross-validation inside the training split. The test columns are "
        "reported for transparency but are not used to choose a model."
        .format(context["cv_folds"])
    )
    add("")

    add("## 14.4 Tuned models (Week 12)")
    add("")
    add(markdown_table(context["tuned_results"]))
    add("")

    add("## 14.5 Final model")
    add("")
    add("- Selected model: **{0}**".format(context["final_model_name"]))
    add("- Selection rule: highest cross-validated R2 on the training split")
    add("- Target transform: `log1p` on fitting, `expm1` on prediction")
    add("")
    add(markdown_table(context["final_metrics_table"]))
    add("")
    add(
        "In plain terms, a typical prediction is off by about {0} on a test "
        "set whose mean selling price is {1}.".format(
            rupees(context["final_metrics"]["MAE"]),
            rupees(context["test_mean_price"]),
        )
    )
    add("")
    add("### Error by price band")
    add("")
    add(markdown_table(context["error_bands"], "{0:.1f}"))
    add("")

    add("## 14.6 Objective check")
    add("")
    verdict, explanation = objective_verdict(context["final_metrics"]["R2"])
    add("**Documented objective: R2 above {0:.0%}. Status: {1}.**".format(
        TARGET_R2, verdict
    ))
    add("")
    add(explanation)
    add("")
    if verdict == "NOT MET":
        add(
            "The reason is a dataset gap rather than a modelling gap. Week 4 "
            "of the project document describes a nine-column CarDekho file "
            "that includes `Present_Price`, the current showroom price of the "
            "same model. The literature scores of 90-95% quoted in Week 3 are "
            "obtained on that file, where `Present_Price` alone explains most "
            "of the resale value. The CSV actually supplied for this project "
            "is the eight-column CarDekho file, which has no such column."
        )
        add("")
        add(
            "Two diagnostics in the table above show where the remaining "
            "error sits. `R2_log` of {0:.4f} scores the same predictions on "
            "the log scale the model is fitted on, and `R2_excl_top1pct` of "
            "{1:.4f} drops the most expensive one percent of test vehicles. "
            "Both are far above the headline R2, which means the model "
            "handles the bulk of the market well and loses most of its score "
            "on a small number of luxury cars whose prices are not "
            "predictable from eight columns.".format(
                context["final_metrics"]["R2_log"],
                context["final_metrics"]["R2_excl_top1pct"],
            )
        )
        add("")
        add("To reach R2 above 0.90 on the rupee scale the project would need:")
        add("")
        add("1. `Present_Price` or an equivalent current-market-value column;")
        add("2. or engine, power, mileage and seats, as in the larger "
            "CarDekho `Car details v3` file;")
        add("3. or a restriction of scope to vehicles under about Rs 15 lakh, "
            "stated explicitly as a scope limit rather than applied silently.")
        add("")

    add("## 14.7 Top features")
    add("")
    add(markdown_table(context["top_features"], "{0:.4f}"))
    add("")

    add("## 14.8 Reproducing this report")
    add("")
    add("```bash")
    add("pip install -r requirements.txt")
    add("python scripts/run_all.py")
    add("```")
    add("")
    add(
        "`run_all.py` runs Weeks 5 to 15 in order and rewrites every artifact "
        "referenced above."
    )
    add("")

    return "\n".join(lines)


def build_presentation_outline(context):
    """Week 15: slide-by-slide outline with the real numbers filled in."""
    metrics = context["final_metrics"]
    verdict, _ = objective_verdict(metrics["R2"])

    lines = []
    add = lines.append

    add("# Week 15 - Final Presentation Outline")
    add("")
    add("Used Car Price Prediction Using Machine Learning (SEML3211)")
    add("")
    add("Twelve slides, roughly one minute each, then the live demo.")
    add("")

    slides = [
        (
            "Title",
            [
                "Used Car Price Prediction Using Machine Learning",
                "Vaibhaw Ojha (24SE02ML287), Yaahvi Parekh (24SE02ML315)",
                "Branch MLAI5D - Foundation of Machine Learning (SEML3211)",
            ],
        ),
        (
            "Problem",
            [
                "Manual used-car valuation varies 15-30% between dealers for "
                "the same vehicle.",
                "Buyers cannot tell whether a listed price is fair; sellers "
                "have no consistent way to set one.",
                "Goal: a data-driven price estimate from vehicle "
                "specifications alone.",
            ],
        ),
        (
            "Dataset",
            [
                "CarDekho vehicle dataset (Kaggle), {0:,} raw records, 8 "
                "columns.".format(context["raw_records"]),
                "{0:,} exact duplicates removed, leaving {1:,} unique "
                "records.".format(
                    context["duplicates_removed"], context["clean_records"]
                ),
                "Target: selling_price, continuous, so this is a regression "
                "problem.",
            ],
        ),
        (
            "EDA findings",
            [
                "Selling price is strongly right-skewed; the log transform "
                "makes it close to symmetric.",
                "Year correlates positively with price; kilometres driven "
                "correlates negatively.",
                "Diesel and automatic vehicles command higher average prices.",
            ],
        ),
        (
            "Feature engineering",
            [
                "car_age, brand, model_family, km_per_year, name_frequency.",
                "name_frequency is fitted on the training split only, so no "
                "test information leaks into training.",
                "Reference year {0} is stored with the model, not recomputed "
                "at prediction time.".format(context["reference_year"]),
            ],
        ),
        (
            "Method",
            [
                "Split first, then engineer features, then fit inside an "
                "sklearn Pipeline.",
                "All estimators fit on log1p(price) and invert on prediction.",
                "Hyper-parameters chosen by {0}-fold cross-validation on the "
                "training split.".format(context["cv_folds"]),
            ],
        ),
        (
            "Model comparison",
            [
                "Five algorithms compared: Linear Regression, Ridge, Decision "
                "Tree, Random Forest, XGBoost.",
                "Plus a stacked ensemble of the tuned models.",
                "Show reports/plots/model_comparison.png.",
            ],
        ),
        (
            "Results",
            [
                "Final model: {0}.".format(context["final_model_name"]),
                "Test R2 {0:.4f}, MAE {1}, RMSE {2}.".format(
                    metrics["R2"], rupees(metrics["MAE"]), rupees(metrics["RMSE"])
                ),
                "R2 on the log scale {0:.4f}; R2 excluding the top 1% of "
                "prices {1:.4f}.".format(
                    metrics["R2_log"], metrics["R2_excl_top1pct"]
                ),
            ],
        ),
        (
            "Honest objective check",
            [
                "Documented objective was R2 above 0.90. Status: {0}.".format(
                    verdict
                ),
                "The 90-95% figures in the literature use Present_Price, a "
                "column the supplied eight-column CSV does not contain.",
                "We report the measured score rather than tuning against the "
                "test set until the number looks right.",
            ],
        ),
        (
            "Feature importance",
            [
                "Top drivers: {0}.".format(context["top_feature_names"]),
                "Matches the domain expectation that age and model line "
                "dominate resale value.",
                "Show reports/feature_importance.csv.",
            ],
        ),
        (
            "Live demo",
            [
                "streamlit run app.py",
                "Enter a vehicle, show the predicted price and the derived "
                "features behind it.",
                "Fallback if Streamlit is unavailable: python "
                "scripts/week13_prototype_check.py",
            ],
        ),
        (
            "Limitations and future work",
            [
                "No condition, service history, accident record or city.",
                "Luxury segment is thinly represented and drives most of the "
                "residual error.",
                "Next: richer schema (engine, power, mileage), then "
                "re-evaluate the 0.90 objective.",
            ],
        ),
    ]

    for index, (title, bullets) in enumerate(slides, start=1):
        add("## Slide {0} - {1}".format(index, title))
        add("")
        for bullet in bullets:
            add("- {0}".format(bullet))
        add("")

    add("## Demo script")
    add("")
    add("1. Start the app: `streamlit run app.py`.")
    add("2. Enter a common vehicle (Maruti Swift Dzire VDI, 2016, 50,000 km).")
    add("3. Point out the derived features shown beside the prediction.")
    add("4. Change the year to 2012 and show the price fall with age.")
    add("5. Change transmission to Automatic and show the price rise.")
    add("6. Enter a name the model has never seen and show that "
        "name_frequency becomes 0 and the prediction still works.")
    add("")

    return "\n".join(lines)


def build_model_card(context):
    """Week 14: a short model card for the appendix."""
    metrics = context["final_metrics"]
    lines = []
    add = lines.append

    add("# Model Card - Used Car Price Predictor")
    add("")
    add("## Overview")
    add("")
    add("| Field | Value |")
    add("| --- | --- |")
    add("| Model | {0} |".format(context["final_model_name"]))
    add("| Task | Regression on selling price, in rupees |")
    add("| Target transform | log1p on fit, expm1 on predict |")
    add("| Training records | {0:,} |".format(context["train_records"]))
    add("| Test records | {0:,} |".format(context["test_records"]))
    add("| Reference year | {0} |".format(context["reference_year"]))
    add("| Random seed | {0} |".format(context["random_state"]))
    add("| Created | {0} |".format(context.get("created_at", "unknown")))
    add("")

    add("## Measured performance (held-out test set)")
    add("")
    add(markdown_table(context["final_metrics_table"]))
    add("")

    add("## Intended use")
    add("")
    add("- Indicative resale estimates for Indian used cars of the kind "
        "listed on CarDekho between 1992 and {0}.".format(
            context["reference_year"]
        ))
    add("- Coursework demonstration of a regression workflow.")
    add("")

    add("## Out of scope")
    add("")
    add("- Any binding valuation, insurance settlement or loan decision.")
    add("- Vehicles above roughly Rs 15 lakh, where the training data is thin "
        "and the error is largest.")
    add("- Markets outside India, and model years after {0}.".format(
        context["reference_year"]
    ))
    add("")

    add("## Known limitations")
    add("")
    add("- The dataset carries no condition, service history, accident record "
        "or city, all of which move real prices.")
    add("- Electric ({0} record) and LPG vehicles are severely "
        "under-represented, so predictions for them are unreliable.".format(
            context["electric_records"]
        ))
    add("- Prices are historical; the model does not track market drift and "
        "will need retraining on newer listings.")
    add("- Measured R2 of {0:.4f} is below the documented 0.90 objective; see "
        "section 14.6 of the final report for why.".format(metrics["R2"]))
    add("")

    return "\n".join(lines)
